Fixes xon,xoff scripts to not even load the extension, when xdebug is off

diff --git a/PHP72-apache-debug/etc/xon b/PHP72-apache-debug/etc/xon
--- a/PHP72-apache-debug/etc/xon
+++ b/PHP72-apache-debug/etc/xon
@@ -5,6 +5,13 @@ then
     rm /usr/local/etc/php/conf.d/xdebug.ini
 fi
 
+if [ ! -f /usr/local/etc/php/docker-php-ext-xdebug.ini.disabled ]; then
+    echo "could not locate xdebug config file. Is xdebug already enabled ?"
+    exit 1
+fi
+
+mv /usr/local/etc/php/docker-php-ext-xdebug.ini.disabled /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
+
 echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/xdebug.ini
 echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug.ini
 echo "xdebug.idekey=PHPSTORM" >> /usr/local/etc/php/conf.d/xdebug.ini
diff --git a/PHP74-apache-debug/etc/xoff b/PHP74-apache-debug/etc/xoff
--- a/PHP74-apache-debug/etc/xoff
+++ b/PHP74-apache-debug/etc/xoff
@@ -5,4 +5,11 @@ then
     rm /usr/local/etc/php/conf.d/xdebug.ini
 fi
 
+if [ ! -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini ]; then
+    echo "Could not locate config file. Is xdebug enabled ?"
+    exit 1
+fi
+
+mv /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini /usr/local/etc/php/docker-php-ext-xdebug.ini.disabled
+
 service apache2 reload
